// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SpellCraft_Core","status":true,"description":"SpellCraft - Core <SpellCraft::Core>","parameters":{"---Time---":"","gameSecondsPerSecond":"10","disableTimeOnDialogue":"true","initialTime":"08:00"}},
{"name":"KhasCore","status":false,"description":"[2.0] Required by Khas plugins.","parameters":{}},
{"name":"KhasGraphics","status":false,"description":"[1.1] Required by Khas graphics plugins.","parameters":{}},
{"name":"KhasUltraLighting","status":false,"description":"[4.2] Adds lighting and real-time shadows to your game.","parameters":{"Custom Blending":"ON","Transfer Reset":"OFF","Auto Battle Lighting":"ON"}}
];
