// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"spellcraft_core","status":true,"description":"SpellCraft - Core <SpellCraft::Core>","parameters":{"---Time---":"","gameSecondsPerSecond":"10","disableTimeOnDialogue":"true","initialTime":"08:00"}}
];
